services:
  ctfd:
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
    depends_on:
      - db
    networks:
        default:
        internal:

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./http.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - ctfd

  db:
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_USER=ctfd
      - POSTGRES_PASSWORD=ctfd
      - POSTGRES_DB=ctfd
    volumes:
      - .data/postgres:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
        default:
        internal:

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    ports:
      - "6379:6379"
    networks:
        default:
        internal:

  sso:
    image: quay.io/keycloak/keycloak:26.2.5
    restart: always
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=sso
    volumes:
      - .data/keycloak:/opt/keycloak/data/
    ports:
      - "8080:8080"
    networks:
        default:
        internal:
    command: [start-dev]

networks:
    default:
    internal:
        internal: true
